### ISSUE TITLE
Birthday

### ISSUE THREAD

**Issue by cdesch** [attics/ruby_attic#2]
I'd be interested in taking over Birthday

**Comment by caonUlisses** [comment]
I saw your issue on Birthday's repo, very nice!
Seems like their e-mail is team@railslove.com

They are keeping other projects active, so I guess they'll respond.

**Comment by bumi** [comment]
Hey I am one of the owner of the bithday gem. Thanks a lot for the interest to support and taking over the maintenance of the gem!
I am super happy to hear that.

The discussion about transferring ownership is here: https://github.com/railslove/birthday/issues/11

And thanks for ruby_attic! that's a great and helpful idea!! 
Maybe we can add a note and some best practices for transferring ownership of a gem here? 
For security reasons I am hesitant to transfer ownership to previous unknown contributors who have not been active yet.

**Comment by caonUlisses** [comment]
Thanks @bumi! 
Good idea! I'll improve both the issue template and the docs later today.

**Comment by caonUlisses** [comment]
Updated! Thanks!!
