### ISSUE TITLE
bootstrap-slider

### ISSUE THREAD

**Issue by weber-s** [attics/ruby_attic#6]
**What project?**

A simple JS library to build nice slider in Bootstrap 3 & 4: https://github.com/seiyria/bootstrap-slider

There used to have a rails gem for it, but it's no more... See here : https://github.com/seiyria/bootstrap-slider#other-platforms--libraries and the RoR project url sending a 404 : https://github.com/YourCursus/bootstrap-slider-rails

**Current status**
- [x] :spider_web: Unmaintained (for rails, but being developed upstream)
- [ ] :juggling_person: Needing help

**How did you check?**
- [ ] I'm the current maintainer
- [ ] I'm a contributor
- [ ] It's written on the README
- [ ] I contacted the current maintainer
- [x] 404 error for the page. The repo doesn't exist anymore.

**Additional context**

It's fairly easy to just copy/past the JS and SASS file, but having it integrated in the Rails assets pipeline and having a simple `bundle update` would be nice!

**Comment by caonUlisses** [comment]
Welcome to ruby_attic! Thank you so much for helping!

**Comment by caonUlisses** [comment]
Added as a 404 project, thanks!
